name = "bot"
type = "webpack"
webpack_config = "webpack.config.js"

account_id = "dff063da5dd1d4b1fa1f5c61ed75876b"
workers_dev = true
route = ""
zone_id = ""

[env.development]
vars={PUBLIC_KEY="74a6ee447f5ad7066aa8782dd670051eed8d18599c04002f00b7372052e26b2d"}