name: Commands

env:
    TOKEN: ${{ secrets.TOKEN }}
    APP: ${{ secrets.APP }}

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'
            - uses: pnpm/action-setup@v2
              with:
                  version: 6.0.2
            - run: pnpm install
            - run: pnpm commands
